"use client";
import { useState, useEffect } from "react";
import Link from "next/link";
import AppNav from "@/components/AppNav";
import { STATE_APPLY_GUIDES, StateApplyGuide, DRAW_RESULT_MONTHS } from "@/lib/applyData";
import { huntingData, SPECIES_LABELS } from "@/lib/huntingData";
import { SpeciesKey } from "@/lib/types";
import { HunterProfile } from "@/app/profile/page";

const PROFILE_KEY = "taghunter_hunter_profile";

const SPECIES_FILTER: { key: SpeciesKey | "all"; label: string }[] = [
  { key: "all",          label: "All Species" },
  { key: "elk",          label: "Elk" },
  { key: "mule_deer",    label: "Mule Deer" },
  { key: "pronghorn",    label: "Pronghorn" },
  { key: "bighorn_sheep",label: "Bighorn Sheep" },
  { key: "mountain_goat",label: "Mountain Goat" },
  { key: "moose",        label: "Moose" },
  { key: "black_bear",   label: "Black Bear" },
];

function getDeadlineForState(stateId: string, species: string): { closeMonth: number; closeDay: number } | null {
  const entry = huntingData.find(d => d.stateId === stateId && d.species === species);
  if (!entry) return null;
  return { closeMonth: entry.appCloseMonth, closeDay: entry.appCloseDay };
}

function buildPrefillCard(profile: HunterProfile, guide: StateApplyGuide, species: string): string {
  const speciesLabel = SPECIES_LABELS[species as SpeciesKey] ?? species;
  const deadline = getDeadlineForState(guide.stateId, species);
  const deadlineStr = deadline
    ? `${DRAW_RESULT_MONTHS[deadline.closeMonth]} ${deadline.closeDay}`
    : "Check state agency";

  const lines: string[] = [
    `╔══════════════════════════════════════════╗`,
    `  ${guide.stateName.toUpperCase()} — ${speciesLabel.toUpperCase()} APPLICATION`,
    `  Tag Hunter Pre-Fill Card`,
    `╚══════════════════════════════════════════╝`,
    ``,
    `PERSONAL INFO`,
    `Name:      ${profile.firstName} ${profile.lastName}`,
    `DOB:       ${profile.dob || "—"}`,
    `Address:   ${profile.address}`,
    `           ${profile.city}, ${profile.residencyState} ${profile.zip}`,
    `Phone:     ${profile.phone || "—"}`,
    `Email:     ${profile.email || "—"}`,
    `SSN Last4: ${profile.ssn4 || "—"}`,
    ``,
    `HUNTER EDUCATION`,
    `Cert #:    ${profile.hunterEdNumber || "—"}`,
    `Issued by: ${profile.hunterEdState || "—"}`,
    ``,
  ];

  const licenseNum = profile.licenses?.[guide.stateId];
  if (licenseNum) {
    lines.push(`${guide.stateName.toUpperCase()} LICENSE`);
    lines.push(`License #: ${licenseNum}`);
    lines.push(``);
  }

  lines.push(`APPLICATION DETAILS`);
  lines.push(`State:     ${guide.stateName}`);
  lines.push(`Species:   ${speciesLabel}`);
  lines.push(`Deadline:  ${deadlineStr}`);
  lines.push(`Portal:    ${guide.portalUrl}`);
  lines.push(``);

  if (guide.specialRequirements.length > 0) {
    lines.push(`BEFORE YOU APPLY`);
    guide.specialRequirements.forEach(r => lines.push(`• ${r}`));
    lines.push(``);
  }

  lines.push(`─────────────────────────────────────────`);
  lines.push(`Generated by Tag Hunter · taghunter.app`);
  lines.push(`Always verify fees & deadlines at official state agency.`);

  return lines.join("\n");
}

const MONTHS = ["", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

function DeadlinePill({ stateId, species }: { stateId: string; species: string }) {
  const dl = getDeadlineForState(stateId, species);
  if (!dl) return null;
  const now = new Date();
  let year = now.getFullYear();
  let closeDate = new Date(year, dl.closeMonth - 1, dl.closeDay);
  if (closeDate < now) { year++; closeDate = new Date(year, dl.closeMonth - 1, dl.closeDay); }
  const days = Math.ceil((closeDate.getTime() - now.getTime()) / 86400000);
  const color = days <= 14 ? "var(--danger)" : days <= 45 ? "var(--warning)" : "var(--success)";
  return (
    <span style={{
      fontSize: 11, fontWeight: 700, padding: "2px 8px",
      borderRadius: 999, background: `${color}18`, border: `1px solid ${color}40`,
      color, whiteSpace: "nowrap",
    }}>
      {MONTHS[dl.closeMonth]} {dl.closeDay} · {days}d
    </span>
  );
}

interface GuideCardProps {
  guide: StateApplyGuide;
  species: string;
  profile: HunterProfile | null;
}

function GuideCard({ guide, species, profile }: GuideCardProps) {
  const [expanded, setExpanded] = useState(false);
  const [copied, setCopied] = useState(false);

  const hasProfile = profile && profile.firstName && profile.lastName;

  const handleCopy = () => {
    if (!profile) return;
    const text = buildPrefillCard(profile, guide, species);
    navigator.clipboard.writeText(text).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    });
  };

  return (
    <div className="card" style={{ overflow: "hidden" }}>
      {/* Card header */}
      <div style={{
        padding: "16px 20px",
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        gap: 12,
        flexWrap: "wrap",
      }}>
        <div style={{ flex: 1, minWidth: 0 }}>
          <div style={{ display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap", marginBottom: 6 }}>
            <span style={{ fontWeight: 800, fontSize: 15, color: "var(--text)" }}>{guide.stateName}</span>
            {species !== "all" && (
              <DeadlinePill stateId={guide.stateId} species={species} />
            )}
            <span style={{
              fontSize: 10, fontWeight: 700, padding: "2px 8px", borderRadius: 999,
              background: "rgba(96,165,250,0.1)", border: "1px solid rgba(96,165,250,0.25)",
              color: "#60a5fa", letterSpacing: "0.05em", textTransform: "uppercase",
            }}>
              Draw Result: {DRAW_RESULT_MONTHS[guide.drawResultMonth]}
            </span>
          </div>
          <p style={{ fontSize: 12, color: "var(--text-3)" }}>{guide.drawResultNote}</p>
        </div>

        <div style={{ display: "flex", gap: 8, flexShrink: 0 }}>
          {hasProfile && (
            <button
              onClick={handleCopy}
              className="btn-ghost"
              style={{ fontSize: 12, padding: "7px 14px" }}
            >
              {copied ? "✓ Copied!" : "📋 Copy Pre-Fill"}
            </button>
          )}
          <a
            href={guide.portalUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="btn-primary"
            style={{ fontSize: 12, padding: "7px 16px" }}
          >
            Apply Now →
          </a>
          <button
            onClick={() => setExpanded(v => !v)}
            style={{
              fontSize: 13, color: "var(--text-3)", background: "none",
              border: "1px solid var(--border)", borderRadius: 8,
              padding: "7px 12px", cursor: "pointer",
            }}
          >
            {expanded ? "▲" : "▼"}
          </button>
        </div>
      </div>

      {/* Expanded guide */}
      {expanded && (
        <div style={{ borderTop: "1px solid var(--border)", padding: "20px" }}>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))", gap: 20 }}>

            {/* What you need */}
            <div>
              <p className="field-label" style={{ marginBottom: 10 }}>What You Need</p>
              <ul style={{ display: "flex", flexDirection: "column", gap: 6, listStyle: "none", padding: 0 }}>
                {guide.requiredFields.map((f, i) => (
                  <li key={i} style={{ fontSize: 12, color: "var(--text-2)", display: "flex", gap: 8, alignItems: "flex-start" }}>
                    <span style={{ color: "var(--text-3)", flexShrink: 0 }}>·</span>
                    {f}
                  </li>
                ))}
              </ul>
            </div>

            {/* Special Requirements */}
            {guide.specialRequirements.length > 0 && (
              <div>
                <p className="field-label" style={{ marginBottom: 10, color: "var(--warning)" }}>Before You Apply</p>
                <ul style={{ display: "flex", flexDirection: "column", gap: 6, listStyle: "none", padding: 0 }}>
                  {guide.specialRequirements.map((r, i) => (
                    <li key={i} style={{ fontSize: 12, color: "var(--text-2)", display: "flex", gap: 8, alignItems: "flex-start" }}>
                      <span style={{ color: "var(--warning)", flexShrink: 0 }}>⚠</span>
                      {r}
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {/* Pro tips */}
            {guide.proTips.length > 0 && (
              <div>
                <p className="field-label" style={{ marginBottom: 10, color: "var(--amber)" }}>Pro Tips</p>
                <ul style={{ display: "flex", flexDirection: "column", gap: 6, listStyle: "none", padding: 0 }}>
                  {guide.proTips.map((t, i) => (
                    <li key={i} style={{ fontSize: 12, color: "var(--text-2)", display: "flex", gap: 8, alignItems: "flex-start" }}>
                      <span style={{ color: "var(--amber)", flexShrink: 0 }}>→</span>
                      {t}
                    </li>
                  ))}
                </ul>
              </div>
            )}

          </div>

          {/* NR note */}
          {guide.nrNotes && (
            <div style={{
              marginTop: 16, padding: "10px 14px",
              background: "rgba(249,115,22,0.06)", border: "1px solid rgba(249,115,22,0.2)",
              borderRadius: 8,
            }}>
              <p style={{ fontSize: 12, color: "var(--text-2)" }}>
                <span style={{ color: "#f97316", fontWeight: 700 }}>NR Note: </span>
                {guide.nrNotes}
              </p>
            </div>
          )}

          <div style={{ marginTop: 16, display: "flex", gap: 10, flexWrap: "wrap" }}>
            <a href={guide.portalUrl} target="_blank" rel="noopener noreferrer"
              style={{ fontSize: 12, color: "var(--amber)" }}>
              {guide.portalLabel} ↗
            </a>
            <span style={{ color: "var(--border)", fontSize: 12 }}>·</span>
            <Link href={`/states/${guide.stateId}`} style={{ fontSize: 12, color: "var(--text-3)" }}>
              State Profile →
            </Link>
          </div>
        </div>
      )}
    </div>
  );
}

export default function ApplyPage() {
  const [speciesFilter, setSpeciesFilter] = useState<SpeciesKey | "all">("elk");
  const [profile, setProfile] = useState<HunterProfile | null>(null);
  const [hasProfile, setHasProfile] = useState(false);

  useEffect(() => {
    try {
      const raw = localStorage.getItem(PROFILE_KEY);
      if (raw) {
        const p = JSON.parse(raw) as HunterProfile;
        setProfile(p);
        setHasProfile(!!(p.firstName && p.lastName));
      }
    } catch {}
  }, []);

  const guides = speciesFilter === "all"
    ? STATE_APPLY_GUIDES
    : STATE_APPLY_GUIDES.filter(g => g.species.includes(speciesFilter));

  const speciesForDeadline = speciesFilter === "all" ? "elk" : speciesFilter;

  // Sort by deadline (ascending) when a specific species is selected
  const sorted = speciesFilter === "all" ? guides : [...guides].sort((a, b) => {
    const da = getDeadlineForState(a.stateId, speciesForDeadline);
    const db = getDeadlineForState(b.stateId, speciesForDeadline);
    if (!da) return 1;
    if (!db) return -1;
    const now = new Date();
    const toDate = (d: { closeMonth: number; closeDay: number }) => {
      let y = now.getFullYear();
      let dt = new Date(y, d.closeMonth - 1, d.closeDay);
      if (dt < now) dt = new Date(y + 1, d.closeMonth - 1, d.closeDay);
      return dt.getTime();
    };
    return toDate(da) - toDate(db);
  });

  return (
    <div className="page">
      <AppNav />
      <div className="page-inner">

        <div style={{ display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: 16, marginBottom: 24, flexWrap: "wrap" }}>
          <div>
            <h1 style={{ fontSize: "1.4rem", fontWeight: 800, letterSpacing: "-0.02em" }}>
              Application Center
            </h1>
            <p style={{ fontSize: 13, color: "var(--text-2)", marginTop: 4 }}>
              Official apply links, step-by-step guides, and pre-fill cards for every state.
            </p>
          </div>
          <Link
            href="/profile"
            className={hasProfile ? "btn-ghost" : "btn-primary"}
            style={{ fontSize: 12, padding: "8px 16px", flexShrink: 0 }}
          >
            {hasProfile ? "✓ Profile Set" : "Set Up Profile →"}
          </Link>
        </div>

        {/* Profile prompt */}
        {!hasProfile && (
          <div className="card" style={{
            padding: "14px 18px",
            marginBottom: 20,
            display: "flex",
            alignItems: "center",
            gap: 14,
            background: "rgba(245,158,11,0.06)",
            borderColor: "rgba(245,158,11,0.25)",
          }}>
            <span style={{ fontSize: "1.4rem", flexShrink: 0 }}>📋</span>
            <div style={{ flex: 1 }}>
              <p style={{ fontWeight: 700, fontSize: 13, color: "var(--amber)", marginBottom: 2 }}>
                Set up your Hunter Profile to unlock pre-fill cards
              </p>
              <p style={{ fontSize: 12, color: "var(--text-3)" }}>
                Fill your info once — Tag Hunter generates a copy-paste card pre-filled with your details for each state application.
              </p>
            </div>
            <Link href="/profile" className="btn-primary" style={{ fontSize: 12, padding: "8px 16px", flexShrink: 0 }}>
              Set Up →
            </Link>
          </div>
        )}

        {/* Species filter */}
        <div style={{ display: "flex", flexWrap: "wrap", gap: 6, marginBottom: 24 }}>
          {SPECIES_FILTER.map(s => (
            <button
              key={s.key}
              onClick={() => setSpeciesFilter(s.key)}
              className={`pill-btn${speciesFilter === s.key ? " selected" : ""}`}
              style={{ fontSize: 12, padding: "6px 14px" }}
            >
              {s.label}
            </button>
          ))}
        </div>

        {/* Info strip */}
        <div style={{
          display: "flex", gap: 20, flexWrap: "wrap",
          padding: "10px 16px", marginBottom: 20,
          background: "var(--card)", border: "1px solid var(--border)",
          borderRadius: 10, fontSize: 12, color: "var(--text-3)",
        }}>
          <span>📍 <strong style={{ color: "var(--text-2)" }}>{sorted.length} states</strong> shown</span>
          <span>🔗 All links go to official state wildlife agency portals</span>
          <span>📋 Pre-fill cards copy to clipboard — no data sent anywhere</span>
        </div>

        {/* Guide cards */}
        <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
          {sorted.map(guide => (
            <GuideCard
              key={guide.stateId}
              guide={guide}
              species={speciesForDeadline}
              profile={profile}
            />
          ))}
        </div>

        <p style={{ textAlign: "center", fontSize: 11, color: "var(--text-3)", marginTop: 32 }}>
          Tag Hunter provides guides only. Always verify deadlines, fees, and requirements at your state&apos;s official wildlife agency before applying.
        </p>

      </div>
    </div>
  );
}
