"use client";
import { useState, useEffect, useCallback } from "react";
import Link from "next/link";
import { useSearchParams, useRouter } from "next/navigation";
import { Suspense } from "react";
import AppNav from "@/components/AppNav";
import DataDisclaimer from "@/components/DataDisclaimer";
import AddApplicationModal from "@/components/AddApplicationModal";
import BudgetDashboard from "@/components/BudgetDashboard";
import PointsTracker from "@/components/PointsTracker";
import HuntLogbook from "@/components/HuntLogbook";
import LicenseTracker from "@/components/LicenseTracker";

// ── shared data ─────────────────────────────────────────────────────────────
import { STATE_APPLY_GUIDES, StateApplyGuide, DRAW_RESULT_MONTHS } from "@/lib/applyData";
import { huntingData, SPECIES_LABELS, STATE_NAMES } from "@/lib/huntingData";
import { SpeciesKey } from "@/lib/types";
import { HunterProfile } from "@/app/profile/page";
import {
  toggleReminder, loadReminders, getUpcomingReminders, DeadlineReminder,
  Application, AppStatus, STATUS_LABELS, STATUS_COLORS,
  loadTracker, updateApplication, deleteApplication,
  deriveCurrentPoints, exportToCSV, CURRENT_YEAR,
} from "@/lib/tracker";

// ─────────────────────────────────────────────────────────────────────────────
// Design tokens
// ─────────────────────────────────────────────────────────────────────────────
const SOIL = "#0F0D0A";
const BARK = "#1A1712";
const FENCE = "#2E2A24";
const AMBER = "#D4852A";
const GLOW = "#F0A040";
const BONE = "#E8DFC8";
const DUST = "#7A6E5F";
const PINE = "#4A7C59";

const DISPLAY = "var(--font-display), Georgia, serif";
const MONO = "var(--font-dm-mono), monospace";

// ─────────────────────────────────────────────────────────────────────────────
// APPLY TAB
// ─────────────────────────────────────────────────────────────────────────────

const PROFILE_KEY = "taghunter_hunter_profile";
const APPLY_MONTHS = ["", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

const APPLY_SPECIES_FILTER: { key: SpeciesKey | "all"; label: string }[] = [
  { key: "all",          label: "All Species" },
  { key: "elk",          label: "Elk" },
  { key: "mule_deer",    label: "Mule Deer" },
  { key: "pronghorn",    label: "Pronghorn" },
  { key: "bighorn_sheep",label: "Bighorn Sheep" },
  { key: "mountain_goat",label: "Mountain Goat" },
  { key: "moose",        label: "Moose" },
  { key: "black_bear",   label: "Black Bear" },
];

function getDeadlineForState(stateId: string, species: string): { closeMonth: number; closeDay: number } | null {
  const entry = huntingData.find(d => d.stateId === stateId && d.species === species);
  if (!entry) return null;
  return { closeMonth: entry.appCloseMonth, closeDay: entry.appCloseDay };
}

function buildPrefillCard(profile: HunterProfile, guide: StateApplyGuide, species: string): string {
  const speciesLabel = SPECIES_LABELS[species as SpeciesKey] ?? species;
  const deadline = getDeadlineForState(guide.stateId, species);
  const deadlineStr = deadline
    ? `${DRAW_RESULT_MONTHS[deadline.closeMonth]} ${deadline.closeDay}`
    : "Check state agency";
  const lines: string[] = [
    `╔══════════════════════════════════════════╗`,
    `  ${guide.stateName.toUpperCase()} — ${speciesLabel.toUpperCase()} APPLICATION`,
    `  Tag Hunter Pre-Fill Card`,
    `╚══════════════════════════════════════════╝`,
    ``,
    `PERSONAL INFO`,
    `Name:      ${profile.firstName} ${profile.lastName}`,
    `DOB:       ${profile.dob || "—"}`,
    `Address:   ${profile.address}`,
    `           ${profile.city}, ${profile.residencyState} ${profile.zip}`,
    `Phone:     ${profile.phone || "—"}`,
    `Email:     ${profile.email || "—"}`,
    `SSN Last4: ${profile.ssn4 || "—"}`,
    ``,
    `HUNTER EDUCATION`,
    `Cert #:    ${profile.hunterEdNumber || "—"}`,
    `Issued by: ${profile.hunterEdState || "—"}`,
    ``,
  ];
  const licenseNum = profile.licenses?.[guide.stateId];
  if (licenseNum) {
    lines.push(`${guide.stateName.toUpperCase()} LICENSE`);
    lines.push(`License #: ${licenseNum}`);
    lines.push(``);
  }
  lines.push(`APPLICATION DETAILS`);
  lines.push(`State:     ${guide.stateName}`);
  lines.push(`Species:   ${speciesLabel}`);
  lines.push(`Deadline:  ${deadlineStr}`);
  lines.push(`Portal:    ${guide.portalUrl}`);
  lines.push(``);
  if (guide.specialRequirements.length > 0) {
    lines.push(`BEFORE YOU APPLY`);
    guide.specialRequirements.forEach(r => lines.push(`• ${r}`));
    lines.push(``);
  }
  lines.push(`─────────────────────────────────────────`);
  lines.push(`Generated by Tag Hunter · taghunter.app`);
  lines.push(`Always verify fees & deadlines at official state agency.`);
  return lines.join("\n");
}

function DeadlinePill({ stateId, species }: { stateId: string; species: string }) {
  const dl = getDeadlineForState(stateId, species);
  if (!dl) return null;
  const now = new Date();
  let year = now.getFullYear();
  let closeDate = new Date(year, dl.closeMonth - 1, dl.closeDay);
  if (closeDate < now) { year++; closeDate = new Date(year, dl.closeMonth - 1, dl.closeDay); }
  const days = Math.ceil((closeDate.getTime() - now.getTime()) / 86400000);
  return (
    <span
      style={{
        fontFamily: MONO,
        fontSize: 10,
        fontWeight: 500,
        letterSpacing: "0.1em",
        textTransform: "uppercase",
        padding: "2px 8px",
        border: `1px solid ${FENCE}`,
        color: DUST,
        whiteSpace: "nowrap",
      }}
    >
      {APPLY_MONTHS[dl.closeMonth]} {dl.closeDay} · {days}d
    </span>
  );
}

function primaryBtnStyle(): React.CSSProperties {
  return {
    background: AMBER,
    color: SOIL,
    fontFamily: MONO,
    fontWeight: 500,
    fontSize: 13,
    padding: "0 16px",
    height: 36,
    border: "none",
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    textDecoration: "none",
    whiteSpace: "nowrap",
  };
}

function ghostBtnStyle(): React.CSSProperties {
  return {
    background: "transparent",
    color: AMBER,
    border: `1px solid ${AMBER}`,
    fontFamily: MONO,
    fontSize: 13,
    padding: "0 16px",
    height: 36,
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    textDecoration: "none",
    whiteSpace: "nowrap",
  };
}

function statusBadgeStyle(): React.CSSProperties {
  return {
    fontFamily: MONO,
    fontSize: 10,
    fontWeight: 500,
    letterSpacing: "0.1em",
    textTransform: "uppercase",
    padding: "2px 8px",
    border: `1px solid ${FENCE}`,
    color: DUST,
    whiteSpace: "nowrap",
    display: "inline-block",
  };
}

function pillStyle(active: boolean): React.CSSProperties {
  return {
    background: active ? AMBER : "transparent",
    color: active ? SOIL : DUST,
    border: `1px solid ${active ? AMBER : FENCE}`,
    fontFamily: MONO,
    fontSize: 12,
    padding: "6px 12px",
    height: 32,
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    whiteSpace: "nowrap",
  };
}

function GuideCard({ guide, species, profile }: { guide: StateApplyGuide; species: string; profile: HunterProfile | null }) {
  const [expanded, setExpanded] = useState(false);
  const [copied, setCopied] = useState(false);
  const hasProfile = profile && profile.firstName && profile.lastName;
  const handleCopy = () => {
    if (!profile) return;
    const text = buildPrefillCard(profile, guide, species);
    navigator.clipboard.writeText(text).then(() => { setCopied(true); setTimeout(() => setCopied(false), 2500); });
  };
  return (
    <div style={{ background: BARK, border: `1px solid ${FENCE}`, marginBottom: 8 }}>
      <div style={{ padding: 20, display: "flex", alignItems: "center", justifyContent: "space-between", gap: 16, flexWrap: "wrap" }}>
        <div style={{ flex: 1, minWidth: 0 }}>
          <div style={{ display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap", marginBottom: 8 }}>
            <span style={{ fontFamily: DISPLAY, fontSize: 18, color: BONE }}>{guide.stateName}</span>
            {species !== "all" && <DeadlinePill stateId={guide.stateId} species={species} />}
            <span style={statusBadgeStyle()}>
              DRAW RESULT: {DRAW_RESULT_MONTHS[guide.drawResultMonth]}
            </span>
          </div>
          <p style={{ fontFamily: MONO, fontSize: 13, color: DUST, marginTop: 8 }}>{guide.drawResultNote}</p>
        </div>
        <div style={{ display: "flex", gap: 8, flexShrink: 0, alignItems: "center" }}>
          {hasProfile && (
            <button onClick={handleCopy} style={ghostBtnStyle()}>
              {copied ? "COPIED" : "PRE-FILL"}
            </button>
          )}
          <a href={guide.portalUrl} target="_blank" rel="noopener noreferrer" style={primaryBtnStyle()}>
            Apply →
          </a>
          <button
            onClick={() => setExpanded(v => !v)}
            style={{
              background: "transparent",
              border: `1px solid ${FENCE}`,
              color: DUST,
              fontFamily: MONO,
              fontSize: 13,
              height: 36,
              width: 36,
              cursor: "pointer",
              display: "inline-flex",
              alignItems: "center",
              justifyContent: "center",
            }}
            onMouseEnter={e => (e.currentTarget.style.color = AMBER)}
            onMouseLeave={e => (e.currentTarget.style.color = DUST)}
            aria-label={expanded ? "Collapse" : "Expand"}
          >
            {expanded ? "▲" : "▼"}
          </button>
        </div>
      </div>
      {expanded && (
        <div style={{ borderTop: `1px solid ${FENCE}`, padding: 20 }}>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))", gap: 20 }}>
            <div>
              <p style={{ fontFamily: MONO, fontSize: 11, color: DUST, textTransform: "uppercase", letterSpacing: "0.15em", marginBottom: 10 }}>What You Need</p>
              <ul style={{ display: "flex", flexDirection: "column", gap: 6, listStyle: "none", padding: 0 }}>
                {guide.requiredFields.map((f, i) => (
                  <li key={i} style={{ fontFamily: MONO, fontSize: 12, color: BONE, display: "flex", gap: 8, alignItems: "flex-start" }}>
                    <span style={{ color: DUST, flexShrink: 0 }}>·</span>{f}
                  </li>
                ))}
              </ul>
            </div>
            {guide.specialRequirements.length > 0 && (
              <div>
                <p style={{ fontFamily: MONO, fontSize: 11, color: AMBER, textTransform: "uppercase", letterSpacing: "0.15em", marginBottom: 10 }}>Before You Apply</p>
                <ul style={{ display: "flex", flexDirection: "column", gap: 6, listStyle: "none", padding: 0 }}>
                  {guide.specialRequirements.map((r, i) => (
                    <li key={i} style={{ fontFamily: MONO, fontSize: 12, color: BONE, display: "flex", gap: 8, alignItems: "flex-start" }}>
                      <span style={{ color: AMBER, flexShrink: 0 }}>!</span>{r}
                    </li>
                  ))}
                </ul>
              </div>
            )}
            {guide.proTips.length > 0 && (
              <div>
                <p style={{ fontFamily: MONO, fontSize: 11, color: AMBER, textTransform: "uppercase", letterSpacing: "0.15em", marginBottom: 10 }}>Pro Tips</p>
                <ul style={{ display: "flex", flexDirection: "column", gap: 6, listStyle: "none", padding: 0 }}>
                  {guide.proTips.map((t, i) => (
                    <li key={i} style={{ fontFamily: MONO, fontSize: 12, color: BONE, display: "flex", gap: 8, alignItems: "flex-start" }}>
                      <span style={{ color: AMBER, flexShrink: 0 }}>→</span>{t}
                    </li>
                  ))}
                </ul>
              </div>
            )}
          </div>
          {guide.nrNotes && (
            <div style={{ marginTop: 16, padding: "12px 14px", background: SOIL, border: `1px solid ${FENCE}` }}>
              <p style={{ fontFamily: MONO, fontSize: 12, color: BONE }}>
                <span style={{ color: AMBER, fontWeight: 500, textTransform: "uppercase", letterSpacing: "0.1em" }}>NR Note: </span>{guide.nrNotes}
              </p>
            </div>
          )}
          <div style={{ marginTop: 16, display: "flex", gap: 10, flexWrap: "wrap", alignItems: "center" }}>
            <a href={guide.portalUrl} target="_blank" rel="noopener noreferrer" style={{ fontFamily: MONO, fontSize: 12, color: AMBER, textDecoration: "none" }}>{guide.portalLabel} ↗</a>
            <span style={{ color: FENCE, fontSize: 12 }}>·</span>
            <Link href={`/states/${guide.stateId}`} style={{ fontFamily: MONO, fontSize: 12, color: DUST, textDecoration: "none" }}>State Profile →</Link>
          </div>
        </div>
      )}
    </div>
  );
}

function ApplyTab() {
  const [speciesFilter, setSpeciesFilter] = useState<SpeciesKey | "all">("elk");
  const [profile, setProfile] = useState<HunterProfile | null>(null);
  const [hasProfile, setHasProfile] = useState(false);
  useEffect(() => {
    try {
      const raw = localStorage.getItem(PROFILE_KEY);
      if (raw) { const p = JSON.parse(raw) as HunterProfile; setProfile(p); setHasProfile(!!(p.firstName && p.lastName)); }
    } catch {}
  }, []);
  const guides = speciesFilter === "all" ? STATE_APPLY_GUIDES : STATE_APPLY_GUIDES.filter(g => g.species.includes(speciesFilter));
  const speciesForDeadline = speciesFilter === "all" ? "elk" : speciesFilter;
  const sorted = speciesFilter === "all" ? guides : [...guides].sort((a, b) => {
    const da = getDeadlineForState(a.stateId, speciesForDeadline);
    const db = getDeadlineForState(b.stateId, speciesForDeadline);
    if (!da) return 1; if (!db) return -1;
    const now = new Date();
    const toDate = (d: { closeMonth: number; closeDay: number }) => { let y = now.getFullYear(); let dt = new Date(y, d.closeMonth - 1, d.closeDay); if (dt < now) dt = new Date(y + 1, d.closeMonth - 1, d.closeDay); return dt.getTime(); };
    return toDate(da) - toDate(db);
  });
  return (
    <div>
      <div style={{ display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: 16, marginBottom: 20, flexWrap: "wrap" }}>
        <p style={{ fontFamily: MONO, fontSize: 13, color: DUST }}>Official apply links, step-by-step guides, and pre-fill cards for every state.</p>
        <Link href="/profile" style={hasProfile ? ghostBtnStyle() : primaryBtnStyle()}>
          {hasProfile ? "PROFILE SET" : "SET UP PROFILE →"}
        </Link>
      </div>
      {!hasProfile && (
        <div style={{ background: BARK, border: `1px solid ${FENCE}`, padding: 20, marginBottom: 20, display: "flex", alignItems: "center", gap: 14 }}>
          <div style={{ width: 20, height: 20, background: AMBER, flexShrink: 0 }} />
          <div style={{ flex: 1 }}>
            <p style={{ fontFamily: MONO, fontWeight: 500, fontSize: 13, color: AMBER, marginBottom: 4 }}>Set up your Hunter Profile to unlock pre-fill cards</p>
            <p style={{ fontFamily: MONO, fontSize: 13, color: DUST }}>Fill your info once — Tag Hunter generates a copy-paste card pre-filled with your details for each state application.</p>
          </div>
          <Link href="/profile" style={primaryBtnStyle()}>SET UP →</Link>
        </div>
      )}
      <div style={{ display: "flex", flexWrap: "wrap", gap: 6, marginBottom: 20 }}>
        {APPLY_SPECIES_FILTER.map(s => (
          <button key={s.key} onClick={() => setSpeciesFilter(s.key)} style={pillStyle(speciesFilter === s.key)}>
            {s.label}
          </button>
        ))}
      </div>
      <div style={{ display: "flex", flexDirection: "column", gap: 0 }}>
        {sorted.map(guide => <GuideCard key={guide.stateId} guide={guide} species={speciesForDeadline} profile={profile} />)}
      </div>
      <p style={{ textAlign: "center", fontFamily: MONO, fontSize: 11, color: DUST, marginTop: 32, letterSpacing: "0.05em" }}>
        Always verify deadlines, fees, and requirements at your state&apos;s official wildlife agency before applying.
      </p>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// DEADLINES TAB
// ─────────────────────────────────────────────────────────────────────────────

const ALL_DL_SPECIES: SpeciesKey[] = ["elk", "mule_deer", "whitetail", "pronghorn", "bighorn_sheep", "mountain_goat", "moose", "black_bear", "bison"];
const DL_MONTH_NAMES = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];
const POINT_SYSTEM_LABELS: Record<string, string> = { preference:"Preference pts", bonus:"Bonus pts", weighted:"Weighted pts", none:"Random lottery", otc:"OTC" };

interface DeadlineItem {
  stateId: string; stateName: string; species: SpeciesKey;
  closeMonth: number; closeDay: number; closeYear: number;
  openMonth: number; feeNonresident: number; hasOTC: boolean;
  pointSystem: string; daysUntil: number; isOpenNow: boolean;
}

function getDeadlines(speciesFilter: SpeciesKey | "all"): DeadlineItem[] {
  const now = new Date(); const today = now.getTime(); const currentMonth = now.getMonth() + 1;
  const seen = new Set<string>(); const deadlines: DeadlineItem[] = [];
  for (const d of huntingData) {
    if (speciesFilter !== "all" && d.species !== speciesFilter) continue;
    const key = `${d.stateId}-${d.species}`; if (seen.has(key)) continue; seen.add(key);
    let year = now.getFullYear();
    let closeDate = new Date(year, d.appCloseMonth - 1, d.appCloseDay);
    if (closeDate.getTime() < today) { year += 1; closeDate = new Date(year, d.appCloseMonth - 1, d.appCloseDay); }
    const daysUntil = Math.ceil((closeDate.getTime() - today) / 86400000);
    let isOpenNow = false;
    if (year === now.getFullYear()) {
      if (d.appOpenMonth <= d.appCloseMonth) isOpenNow = currentMonth >= d.appOpenMonth && currentMonth <= d.appCloseMonth && closeDate.getTime() > today;
    } else { isOpenNow = currentMonth >= d.appOpenMonth; }
    deadlines.push({ stateId: d.stateId, stateName: d.stateName, species: d.species as SpeciesKey, closeMonth: d.appCloseMonth, closeDay: d.appCloseDay, closeYear: year, openMonth: d.appOpenMonth, feeNonresident: d.feeNonresident, hasOTC: d.hasOTC, pointSystem: d.pointSystem, daysUntil, isOpenNow });
  }
  return deadlines.sort((a, b) => a.daysUntil - b.daysUntil);
}

function DeadlineCard({ d, watched, onToggle, highlight }: { d: DeadlineItem; watched: boolean; onToggle: () => void; highlight?: boolean }) {
  const borderColor = highlight ? PINE : FENCE;
  return (
    <div style={{
      background: BARK,
      border: `1px solid ${borderColor}`,
      padding: 20,
      marginBottom: 8,
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 16,
    }}>
      <div style={{ flex: 1, minWidth: 0 }}>
        <div style={{ display: "flex", flexWrap: "wrap", alignItems: "center", gap: 10, marginBottom: 8 }}>
          <span style={{ fontFamily: DISPLAY, fontSize: 18, color: BONE }}>{d.stateName}</span>
          <span style={{ fontFamily: MONO, fontSize: 13, color: DUST }}>{SPECIES_LABELS[d.species]}</span>
          {d.isOpenNow && (
            <span style={{ ...statusBadgeStyle(), borderColor: PINE, color: PINE }}>OPEN NOW</span>
          )}
          {d.hasOTC && <span style={statusBadgeStyle()}>OTC</span>}
        </div>
        <div style={{ display: "flex", flexWrap: "wrap", gap: 10, fontFamily: MONO, fontSize: 11, color: DUST, textTransform: "uppercase", letterSpacing: "0.1em" }}>
          <span>Closes {DL_MONTH_NAMES[d.closeMonth - 1]} {d.closeDay}, {d.closeYear}</span>
          <span>·</span><span>NR ${d.feeNonresident.toLocaleString()}</span>
          <span>·</span><span>{POINT_SYSTEM_LABELS[d.pointSystem] ?? d.pointSystem}</span>
        </div>
      </div>
      <div style={{ display: "flex", alignItems: "center", gap: 16, flexShrink: 0 }}>
        <button
          onClick={onToggle}
          title={watched ? "Remove reminder" : "Set reminder"}
          style={{
            fontFamily: MONO,
            fontSize: 10,
            fontWeight: 500,
            letterSpacing: "0.1em",
            textTransform: "uppercase",
            padding: "4px 10px",
            background: "transparent",
            color: watched ? AMBER : DUST,
            border: `1px solid ${watched ? AMBER : FENCE}`,
            cursor: "pointer",
          }}
        >
          {watched ? "WATCHING" : "REMIND"}
        </button>
        <div style={{ textAlign: "right" }}>
          <div style={{ fontFamily: DISPLAY, fontSize: 24, color: BONE, lineHeight: 1 }}>{d.daysUntil}d</div>
          <div style={{ fontFamily: MONO, fontSize: 10, color: DUST, marginTop: 4, textTransform: "uppercase", letterSpacing: "0.1em" }}>
            {d.daysUntil <= 14 ? "Closing soon" : d.daysUntil <= 45 ? "Coming up" : "Upcoming"}
          </div>
        </div>
      </div>
    </div>
  );
}

function DeadlinesTab() {
  const [speciesFilter, setSpeciesFilter] = useState<SpeciesKey | "all">("elk");
  const [watchedKeys, setWatchedKeys] = useState<Set<string>>(new Set());
  const [alertDismissed, setAlertDismissed] = useState(false);
  const [upcomingReminders, setUpcomingReminders] = useState<DeadlineReminder[]>([]);
  useEffect(() => { const r = loadReminders(); setWatchedKeys(new Set(r.map(x => x.key))); setUpcomingReminders(getUpcomingReminders(14)); }, []);
  const deadlines = getDeadlines(speciesFilter);
  const openNow = deadlines.filter(d => d.isOpenNow);
  const upcoming = deadlines.filter(d => !d.isOpenNow && d.daysUntil <= 60);
  const later = deadlines.filter(d => !d.isOpenNow && d.daysUntil > 60);
  const handleToggleReminder = (d: DeadlineItem) => {
    const key = `${d.stateId}-${d.species}`;
    const reminder: DeadlineReminder = { key, stateName: d.stateName, species: d.species, closeMonth: d.closeMonth, closeDay: d.closeDay };
    const nowWatching = toggleReminder(reminder);
    setWatchedKeys(prev => { const next = new Set(prev); if (nowWatching) next.add(key); else next.delete(key); return next; });
    setUpcomingReminders(getUpcomingReminders(14));
  };
  const handleExportIcal = () => {
    const lines = ["BEGIN:VCALENDAR","VERSION:2.0","PRODID:-//Tag Hunter//Hunt Application Deadlines//EN","CALSCALE:GREGORIAN"];
    for (const d of deadlines) {
      const dt = `${d.closeYear}${String(d.closeMonth).padStart(2,"0")}${String(d.closeDay).padStart(2,"0")}`;
      lines.push("BEGIN:VEVENT",`UID:taghunter-${d.stateId}-${d.species}-${d.closeYear}@taghunter.app`,`DTSTART;VALUE=DATE:${dt}`,`DTEND;VALUE=DATE:${dt}`,`SUMMARY:${d.stateName} ${SPECIES_LABELS[d.species]} Application Closes`,`DESCRIPTION:NR Fee: $${d.feeNonresident}`,`END:VEVENT`);
    }
    lines.push("END:VCALENDAR");
    const blob = new Blob([lines.join("\r\n")], { type: "text/calendar;charset=utf-8" });
    const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = "taghunter-deadlines.ics"; a.click(); URL.revokeObjectURL(url);
  };
  const sectionLabelStyle: React.CSSProperties = {
    fontFamily: MONO,
    fontSize: 11,
    fontWeight: 500,
    textTransform: "uppercase",
    letterSpacing: "0.15em",
    color: DUST,
    marginBottom: 12,
  };
  return (
    <div>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 16, gap: 16, flexWrap: "wrap" }}>
        <p style={{ fontFamily: MONO, fontSize: 13, color: DUST }}>Never miss an application window</p>
        <button onClick={handleExportIcal} style={ghostBtnStyle()}>EXPORT .ICS</button>
      </div>
      <DataDisclaimer />
      {!alertDismissed && upcomingReminders.length > 0 && (
        <div style={{ background: BARK, border: `1px solid ${AMBER}`, padding: 20, marginBottom: 20, display: "flex", alignItems: "flex-start", gap: 14 }}>
          <div style={{ width: 20, height: 20, background: AMBER, flexShrink: 0 }} />
          <div style={{ flex: 1 }}>
            <p style={{ fontFamily: MONO, fontWeight: 500, fontSize: 13, color: AMBER, marginBottom: 8 }}>Upcoming deadline reminders</p>
            <ul style={{ listStyle: "none", display: "flex", flexDirection: "column", gap: 6, padding: 0 }}>
              {upcomingReminders.map(r => {
                const now = new Date(); let year = now.getFullYear(); let d = new Date(year, r.closeMonth - 1, r.closeDay); if (d < now) { year += 1; d = new Date(year, r.closeMonth - 1, r.closeDay); }
                const days = Math.ceil((d.getTime() - now.getTime()) / 86400000);
                return <li key={r.key} style={{ fontFamily: MONO, fontSize: 12, color: BONE }}>{r.stateName} {SPECIES_LABELS[r.species]} — closes {DL_MONTH_NAMES[r.closeMonth - 1]} {r.closeDay}<span style={{ color: AMBER, marginLeft: 6 }}>({days}d)</span></li>;
              })}
            </ul>
          </div>
          <button
            onClick={() => setAlertDismissed(true)}
            style={{ fontFamily: MONO, fontSize: 14, color: DUST, background: "none", border: "none", cursor: "pointer" }}
            aria-label="Dismiss"
          >
            ×
          </button>
        </div>
      )}
      <div style={{ display: "flex", flexWrap: "wrap", gap: 6, marginBottom: 20 }}>
        {(["all", ...ALL_DL_SPECIES] as (SpeciesKey | "all")[]).map(s => (
          <button key={s} onClick={() => setSpeciesFilter(s)} style={pillStyle(speciesFilter === s)}>
            {s === "all" ? "All Species" : SPECIES_LABELS[s]}
          </button>
        ))}
      </div>
      {openNow.length > 0 && (
        <div style={{ marginBottom: 24 }}>
          <p style={{ ...sectionLabelStyle, color: PINE }}>Apply Right Now</p>
          <div style={{ display: "flex", flexDirection: "column", gap: 0 }}>
            {openNow.map(d => { const key = `${d.stateId}-${d.species}`; return <DeadlineCard key={key} d={d} watched={watchedKeys.has(key)} onToggle={() => handleToggleReminder(d)} highlight />; })}
          </div>
        </div>
      )}
      {upcoming.length > 0 && (
        <div style={{ marginBottom: 24 }}>
          <p style={{ ...sectionLabelStyle, color: AMBER }}>Next 60 Days</p>
          <div style={{ display: "flex", flexDirection: "column", gap: 0 }}>
            {upcoming.map(d => { const key = `${d.stateId}-${d.species}`; return <DeadlineCard key={key} d={d} watched={watchedKeys.has(key)} onToggle={() => handleToggleReminder(d)} />; })}
          </div>
        </div>
      )}
      {later.length > 0 && (
        <div>
          <p style={sectionLabelStyle}>Later This Season</p>
          <div style={{ display: "flex", flexDirection: "column", gap: 0 }}>
            {later.map(d => { const key = `${d.stateId}-${d.species}`; return <DeadlineCard key={key} d={d} watched={watchedKeys.has(key)} onToggle={() => handleToggleReminder(d)} />; })}
          </div>
        </div>
      )}
      <p style={{ textAlign: "center", fontFamily: MONO, fontSize: 11, color: DUST, marginTop: 32, letterSpacing: "0.05em" }}>Always verify deadlines at your state&apos;s official wildlife agency website before applying.</p>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// MY APPLICATIONS TAB
// ─────────────────────────────────────────────────────────────────────────────

type SortKey = "year" | "state" | "species" | "status";

function TrackerTab() {
  const [apps, setApps] = useState<Application[]>([]);
  const [showAdd, setShowAdd] = useState(false);
  const [filterYear, setFilterYear] = useState<number | "all">("all");
  const [filterSpecies, setFilterSpecies] = useState<SpeciesKey | "all">("all");
  const [filterStatus, setFilterStatus] = useState<AppStatus | "all">("all");
  const [sortKey, setSortKey] = useState<SortKey>("year");
  const [confirmDeleteId, setConfirmDeleteId] = useState<string | null>(null);
  const reload = useCallback(() => { const data = loadTracker(); setApps(data.applications); }, []);
  useEffect(() => { reload(); }, [reload]);
  const handleStatusChange = (id: string, status: AppStatus) => { updateApplication(id, { status }); reload(); };
  const handleDelete = (id: string) => { deleteApplication(id); setConfirmDeleteId(null); reload(); };
  const totalFees = apps.reduce((s, a) => s + (a.feeSpent || 0), 0);
  const drawn = apps.filter(a => a.status === "drawn").length;
  const thisYear = apps.filter(a => a.year === CURRENT_YEAR);
  const pending = apps.filter(a => a.status === "applied" || a.status === "pending");
  const currentPoints = deriveCurrentPoints(apps);
  const years = [...new Set(apps.map(a => a.year))].sort((a, b) => b - a);
  const allSpecies = [...new Set(apps.map(a => a.species))] as SpeciesKey[];
  const filtered = apps
    .filter(a => filterYear === "all" || a.year === filterYear)
    .filter(a => filterSpecies === "all" || a.species === filterSpecies)
    .filter(a => filterStatus === "all" || a.status === filterStatus)
    .sort((a, b) => {
      if (sortKey === "year") return b.year - a.year;
      if (sortKey === "state") return a.stateName.localeCompare(b.stateName);
      if (sortKey === "species") return a.species.localeCompare(b.species);
      if (sortKey === "status") return a.status.localeCompare(b.status);
      return 0;
    });
  const selectStyle: React.CSSProperties = {
    background: BARK,
    color: BONE,
    border: `1px solid ${FENCE}`,
    fontFamily: MONO,
    fontSize: 12,
    padding: "6px 10px",
    height: 32,
    width: "auto",
  };
  return (
    <div>
      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 20, gap: 16, flexWrap: "wrap" }}>
        <p style={{ fontFamily: MONO, fontSize: 13, color: DUST }}>Track points, draws, and licenses — stored in your browser</p>
        <div style={{ display: "flex", gap: 8 }}>
          {apps.length > 0 && <button onClick={() => exportToCSV(apps)} style={ghostBtnStyle()}>EXPORT CSV</button>}
          <button onClick={() => setShowAdd(true)} style={primaryBtnStyle()}>+ LOG APPLICATION</button>
        </div>
      </div>
      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(140px, 1fr))", gap: 8, marginBottom: 24 }}>
        {[
          { label: "Total Applications", value: String(apps.length) },
          { label: "Tags Drawn", value: `${drawn} / ${apps.length}` },
          { label: `${CURRENT_YEAR} Apps`, value: String(thisYear.length) },
          { label: "Fees (All Time)", value: `$${totalFees.toLocaleString()}` },
        ].map(s => (
          <div key={s.label} style={{ background: BARK, border: `1px solid ${FENCE}`, padding: 20 }}>
            <div style={{ fontFamily: DISPLAY, fontSize: 28, color: BONE, lineHeight: 1 }}>{s.value}</div>
            <div style={{ fontFamily: MONO, fontSize: 10, color: DUST, marginTop: 8, textTransform: "uppercase", letterSpacing: "0.15em" }}>{s.label}</div>
          </div>
        ))}
      </div>
      {pending.length > 0 && (
        <div style={{ background: BARK, border: `1px solid ${AMBER}`, padding: 20, marginBottom: 20, display: "flex", alignItems: "flex-start", gap: 14 }}>
          <div style={{ width: 20, height: 20, background: AMBER, flexShrink: 0 }} />
          <div>
            <p style={{ fontFamily: MONO, fontWeight: 500, fontSize: 13, color: AMBER }}>{pending.length} application{pending.length > 1 ? "s" : ""} awaiting results</p>
            <p style={{ fontFamily: MONO, fontSize: 13, color: DUST, marginTop: 6 }}>{pending.map(a => `${a.stateName} ${SPECIES_LABELS[a.species as SpeciesKey]}`).join(" · ")}</p>
          </div>
        </div>
      )}
      <BudgetDashboard apps={apps} />
      <PointsTracker apps={apps} />
      <LicenseTracker />
      <HuntLogbook />
      {Object.keys(currentPoints).length > 0 && (
        <div style={{ background: BARK, border: `1px solid ${FENCE}`, padding: 20, marginBottom: 20 }}>
          <h3 style={{ fontFamily: MONO, fontSize: 11, fontWeight: 500, textTransform: "uppercase", letterSpacing: "0.15em", color: DUST, marginBottom: 14 }}>Current Points (derived from history)</h3>
          <div style={{ display: "flex", flexWrap: "wrap", gap: 8 }}>
            {Object.entries(currentPoints).flatMap(([stateId, speciesMap]) =>
              Object.entries(speciesMap).map(([species, pts]) => (
                <div key={`${stateId}-${species}`} style={{ fontFamily: MONO, fontSize: 11, padding: "4px 10px", border: `1px solid ${FENCE}`, color: DUST, textTransform: "uppercase", letterSpacing: "0.1em" }}>
                  <span style={{ color: BONE }}>{STATE_NAMES[stateId.toUpperCase()] ?? stateId}</span>
                  <span style={{ color: DUST, margin: "0 4px" }}>·</span>
                  <span style={{ color: DUST }}>{SPECIES_LABELS[species as SpeciesKey]}</span>
                  <span style={{ color: AMBER, fontWeight: 500, marginLeft: 6 }}>{pts}pt</span>
                </div>
              ))
            )}
          </div>
        </div>
      )}
      {apps.length > 0 && (
        <div style={{ display: "flex", flexWrap: "wrap", gap: 8, marginBottom: 16, alignItems: "center" }}>
          <select value={filterYear} onChange={e => setFilterYear(e.target.value === "all" ? "all" : Number(e.target.value))} style={selectStyle}>
            <option value="all">All Years</option>
            {years.map(y => <option key={y} value={y}>{y}</option>)}
          </select>
          <select value={filterSpecies} onChange={e => setFilterSpecies(e.target.value as SpeciesKey | "all")} style={selectStyle}>
            <option value="all">All Species</option>
            {allSpecies.map(s => <option key={s} value={s}>{SPECIES_LABELS[s]}</option>)}
          </select>
          <select value={filterStatus} onChange={e => setFilterStatus(e.target.value as AppStatus | "all")} style={selectStyle}>
            <option value="all">All Statuses</option>
            {(Object.keys(STATUS_LABELS) as AppStatus[]).map(s => <option key={s} value={s}>{STATUS_LABELS[s]}</option>)}
          </select>
          <div style={{ marginLeft: "auto", display: "flex", alignItems: "center", gap: 6, fontFamily: MONO, fontSize: 11, color: DUST, textTransform: "uppercase", letterSpacing: "0.1em" }}>
            Sort:
            {(["year","state","species","status"] as SortKey[]).map(k => (
              <button
                key={k}
                onClick={() => setSortKey(k)}
                style={{
                  padding: "4px 10px",
                  fontFamily: MONO,
                  fontSize: 11,
                  textTransform: "uppercase",
                  letterSpacing: "0.1em",
                  background: sortKey === k ? AMBER : "transparent",
                  color: sortKey === k ? SOIL : DUST,
                  border: `1px solid ${sortKey === k ? AMBER : FENCE}`,
                  cursor: "pointer",
                }}
              >
                {k}
              </button>
            ))}
          </div>
        </div>
      )}
      {apps.length === 0 ? (
        <div style={{ background: BARK, border: `1px solid ${FENCE}`, padding: 56, textAlign: "center" }}>
          <p style={{ fontFamily: DISPLAY, fontSize: 24, color: BONE, marginBottom: 12 }}>No applications logged yet</p>
          <p style={{ fontFamily: MONO, fontSize: 13, color: DUST, marginBottom: 24, maxWidth: 400, margin: "0 auto 24px" }}>Track every state application, watch your points grow, and never miss a deadline.</p>
          <button onClick={() => setShowAdd(true)} style={primaryBtnStyle()}>LOG YOUR FIRST APPLICATION</button>
        </div>
      ) : (
        <div style={{ display: "flex", flexDirection: "column", gap: 0 }}>
          {filtered.length === 0 && <p style={{ textAlign: "center", padding: "32px 0", fontFamily: MONO, fontSize: 13, color: DUST }}>No applications match the current filters.</p>}
          {filtered.map(app => {
            const colors = STATUS_COLORS[app.status];
            const isConfirmingDelete = confirmDeleteId === app.id;
            return (
              <div key={app.id} style={{ background: BARK, border: `1px solid ${FENCE}`, padding: 20, marginBottom: 8 }}>
                <div style={{ display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: 16, flexWrap: "wrap" }}>
                  <div style={{ flex: 1, minWidth: 0 }}>
                    <div style={{ display: "flex", flexWrap: "wrap", alignItems: "center", gap: 10, marginBottom: 8 }}>
                      <span style={{ fontFamily: MONO, fontSize: 11, color: DUST, textTransform: "uppercase", letterSpacing: "0.1em" }}>{app.year}</span>
                      <span style={{ fontFamily: DISPLAY, fontSize: 18, color: BONE }}>{app.stateName}</span>
                      <span style={{ fontFamily: MONO, fontSize: 13, color: DUST }}>{SPECIES_LABELS[app.species as SpeciesKey]}</span>
                      <span style={{ fontFamily: MONO, fontSize: 11, color: DUST, textTransform: "uppercase", letterSpacing: "0.1em" }}>{app.seasonType}</span>
                    </div>
                    <div style={{ display: "flex", flexWrap: "wrap", gap: 14, fontFamily: MONO, fontSize: 12, color: DUST }}>
                      {app.pointsBefore >= 0 && (
                        <span>Points: <span style={{ color: BONE }}>{app.pointsBefore}</span>
                          {app.pointsAfter !== app.pointsBefore && (
                            <span> → <span style={{ color: app.status === "drawn" ? AMBER : PINE }}>{app.pointsAfter}</span></span>
                          )}
                        </span>
                      )}
                      {app.feeSpent > 0 && <span>Fee: <span style={{ color: BONE }}>${app.feeSpent}</span></span>}
                      {app.appliedDate && <span>Applied: <span style={{ color: BONE }}>{app.appliedDate}</span></span>}
                      {app.notes && <span style={{ fontStyle: "italic" }}>&quot;{app.notes}&quot;</span>}
                    </div>
                  </div>
                  <div style={{ display: "flex", flexDirection: "column", alignItems: "flex-end", gap: 8, flexShrink: 0 }}>
                    <span style={{ ...statusBadgeStyle(), borderColor: colors.border, color: colors.text }}>{STATUS_LABELS[app.status]}</span>
                    {(app.status === "applied" || app.status === "pending") && (
                      <div style={{ display: "flex", gap: 6 }}>
                        <button
                          onClick={() => handleStatusChange(app.id, "drawn")}
                          style={{
                            fontFamily: MONO,
                            fontSize: 10,
                            textTransform: "uppercase",
                            letterSpacing: "0.1em",
                            padding: "4px 10px",
                            background: "transparent",
                            color: PINE,
                            border: `1px solid ${PINE}`,
                            cursor: "pointer",
                          }}
                        >
                          Drawn
                        </button>
                        <button
                          onClick={() => handleStatusChange(app.id, "not_drawn")}
                          style={{
                            fontFamily: MONO,
                            fontSize: 10,
                            textTransform: "uppercase",
                            letterSpacing: "0.1em",
                            padding: "4px 10px",
                            background: "transparent",
                            color: DUST,
                            border: `1px solid ${FENCE}`,
                            cursor: "pointer",
                          }}
                        >
                          Not Drawn
                        </button>
                      </div>
                    )}
                    {isConfirmingDelete ? (
                      <div style={{ display: "flex", gap: 6 }}>
                        <button
                          onClick={() => handleDelete(app.id)}
                          style={{
                            fontFamily: MONO,
                            fontSize: 10,
                            textTransform: "uppercase",
                            letterSpacing: "0.1em",
                            padding: "4px 10px",
                            background: AMBER,
                            color: SOIL,
                            border: `1px solid ${AMBER}`,
                            cursor: "pointer",
                          }}
                        >
                          Confirm
                        </button>
                        <button
                          onClick={() => setConfirmDeleteId(null)}
                          style={{ fontFamily: MONO, fontSize: 10, textTransform: "uppercase", letterSpacing: "0.1em", color: DUST, cursor: "pointer", background: "none", border: "none" }}
                        >
                          Cancel
                        </button>
                      </div>
                    ) : (
                      <button
                        onClick={() => setConfirmDeleteId(app.id)}
                        style={{ fontFamily: MONO, fontSize: 10, textTransform: "uppercase", letterSpacing: "0.1em", color: DUST, cursor: "pointer", background: "none", border: "none" }}
                      >
                        Delete
                      </button>
                    )}
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      )}
      <p style={{ textAlign: "center", fontFamily: MONO, fontSize: 11, color: DUST, marginTop: 32, letterSpacing: "0.05em" }}>Data stored locally in your browser. Use Export CSV to back up your records.</p>
      {showAdd && <AddApplicationModal onClose={() => setShowAdd(false)} onAdded={() => { reload(); setShowAdd(false); }} />}
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// DASHBOARD PAGE
// ─────────────────────────────────────────────────────────────────────────────

type Tab = "apply" | "deadlines" | "tracker";

const TAB_CONFIG: { key: Tab; label: string }[] = [
  { key: "apply",     label: "Apply" },
  { key: "deadlines", label: "Deadlines" },
  { key: "tracker",   label: "My Applications" },
];

function TabButton({ active, label, onClick }: { active: boolean; label: string; onClick: () => void }) {
  const [hover, setHover] = useState(false);
  const color = active ? AMBER : (hover ? BONE : DUST);
  return (
    <button
      onClick={onClick}
      onMouseEnter={() => setHover(true)}
      onMouseLeave={() => setHover(false)}
      style={{
        padding: "14px 20px",
        fontFamily: MONO,
        fontWeight: 500,
        fontSize: 12,
        textTransform: "uppercase",
        letterSpacing: "0.15em",
        color,
        background: "none",
        border: "none",
        borderBottom: active ? `2px solid ${AMBER}` : "2px solid transparent",
        cursor: "pointer",
        marginBottom: -1,
        whiteSpace: "nowrap",
        transition: "color 0.15s",
      }}
    >
      {label}
    </button>
  );
}

function DashboardInner() {
  const searchParams = useSearchParams();
  const router = useRouter();
  const rawTab = searchParams.get("tab");
  const activeTab: Tab = (rawTab === "apply" || rawTab === "deadlines" || rawTab === "tracker") ? rawTab : "apply";

  const setTab = (t: Tab) => {
    const params = new URLSearchParams(searchParams.toString());
    params.set("tab", t);
    router.replace(`/dashboard?${params.toString()}`, { scroll: false });
  };

  return (
    <div className="page" style={{ background: SOIL, color: BONE, fontFamily: MONO, minHeight: "100vh" }}>
      <AppNav />
      <div className="page-inner-wide" style={{ maxWidth: 1100, margin: "0 auto", padding: "0 24px 64px" }}>

        {/* Page header */}
        <div style={{ padding: "40px 0 24px" }}>
          <h1 style={{ fontFamily: DISPLAY, fontSize: 42, fontWeight: 700, letterSpacing: "-0.02em", color: BONE, lineHeight: 1.1 }}>Dashboard</h1>
          <p style={{ fontFamily: MONO, fontSize: 14, color: DUST, marginTop: 8 }}>Apply, track deadlines, and manage your applications in one place.</p>
        </div>

        {/* Tab bar */}
        <div style={{ display: "flex", gap: 0, borderBottom: `1px solid ${FENCE}`, marginBottom: 24 }}>
          {TAB_CONFIG.map(t => (
            <TabButton key={t.key} active={activeTab === t.key} label={t.label} onClick={() => setTab(t.key)} />
          ))}
        </div>

        {/* Tab content */}
        {activeTab === "apply"     && <ApplyTab />}
        {activeTab === "deadlines" && <DeadlinesTab />}
        {activeTab === "tracker"   && <TrackerTab />}

      </div>
    </div>
  );
}

export default function DashboardPage() {
  return (
    <Suspense fallback={
      <div style={{ minHeight: "100vh", display: "flex", alignItems: "center", justifyContent: "center", background: SOIL, color: DUST, fontFamily: MONO }}>
        Loading...
      </div>
    }>
      <DashboardInner />
    </Suspense>
  );
}
