"use client";
import { useState, useEffect, useCallback } from "react";
import Link from "next/link";
import { useSearchParams, useRouter } from "next/navigation";
import { Suspense } from "react";
import AppNav from "@/components/AppNav";
import DataDisclaimer from "@/components/DataDisclaimer";
import AddApplicationModal from "@/components/AddApplicationModal";
import BudgetDashboard from "@/components/BudgetDashboard";
import PointsTracker from "@/components/PointsTracker";
import HuntLogbook from "@/components/HuntLogbook";
import LicenseTracker from "@/components/LicenseTracker";

// ── shared data ─────────────────────────────────────────────────────────────
import { STATE_APPLY_GUIDES, StateApplyGuide, DRAW_RESULT_MONTHS } from "@/lib/applyData";
import { huntingData, SPECIES_LABELS, STATE_NAMES } from "@/lib/huntingData";
import { SpeciesKey } from "@/lib/types";
import { HunterProfile } from "@/app/profile/page";
import {
  toggleReminder, loadReminders, getUpcomingReminders, DeadlineReminder,
  Application, AppStatus, STATUS_LABELS, STATUS_COLORS,
  loadTracker, updateApplication, deleteApplication,
  deriveCurrentPoints, exportToCSV, CURRENT_YEAR,
} from "@/lib/tracker";

// ─────────────────────────────────────────────────────────────────────────────
// APPLY TAB
// ─────────────────────────────────────────────────────────────────────────────

const PROFILE_KEY = "taghunter_hunter_profile";
const APPLY_MONTHS = ["", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

const APPLY_SPECIES_FILTER: { key: SpeciesKey | "all"; label: string }[] = [
  { key: "all",          label: "All Species" },
  { key: "elk",          label: "Elk" },
  { key: "mule_deer",    label: "Mule Deer" },
  { key: "pronghorn",    label: "Pronghorn" },
  { key: "bighorn_sheep",label: "Bighorn Sheep" },
  { key: "mountain_goat",label: "Mountain Goat" },
  { key: "moose",        label: "Moose" },
  { key: "black_bear",   label: "Black Bear" },
];

function getDeadlineForState(stateId: string, species: string): { closeMonth: number; closeDay: number } | null {
  const entry = huntingData.find(d => d.stateId === stateId && d.species === species);
  if (!entry) return null;
  return { closeMonth: entry.appCloseMonth, closeDay: entry.appCloseDay };
}

function buildPrefillCard(profile: HunterProfile, guide: StateApplyGuide, species: string): string {
  const speciesLabel = SPECIES_LABELS[species as SpeciesKey] ?? species;
  const deadline = getDeadlineForState(guide.stateId, species);
  const deadlineStr = deadline
    ? `${DRAW_RESULT_MONTHS[deadline.closeMonth]} ${deadline.closeDay}`
    : "Check state agency";
  const lines: string[] = [
    `╔══════════════════════════════════════════╗`,
    `  ${guide.stateName.toUpperCase()} — ${speciesLabel.toUpperCase()} APPLICATION`,
    `  Tag Hunter Pre-Fill Card`,
    `╚══════════════════════════════════════════╝`,
    ``,
    `PERSONAL INFO`,
    `Name:      ${profile.firstName} ${profile.lastName}`,
    `DOB:       ${profile.dob || "—"}`,
    `Address:   ${profile.address}`,
    `           ${profile.city}, ${profile.residencyState} ${profile.zip}`,
    `Phone:     ${profile.phone || "—"}`,
    `Email:     ${profile.email || "—"}`,
    `SSN Last4: ${profile.ssn4 || "—"}`,
    ``,
    `HUNTER EDUCATION`,
    `Cert #:    ${profile.hunterEdNumber || "—"}`,
    `Issued by: ${profile.hunterEdState || "—"}`,
    ``,
  ];
  const licenseNum = profile.licenses?.[guide.stateId];
  if (licenseNum) {
    lines.push(`${guide.stateName.toUpperCase()} LICENSE`);
    lines.push(`License #: ${licenseNum}`);
    lines.push(``);
  }
  lines.push(`APPLICATION DETAILS`);
  lines.push(`State:     ${guide.stateName}`);
  lines.push(`Species:   ${speciesLabel}`);
  lines.push(`Deadline:  ${deadlineStr}`);
  lines.push(`Portal:    ${guide.portalUrl}`);
  lines.push(``);
  if (guide.specialRequirements.length > 0) {
    lines.push(`BEFORE YOU APPLY`);
    guide.specialRequirements.forEach(r => lines.push(`• ${r}`));
    lines.push(``);
  }
  lines.push(`─────────────────────────────────────────`);
  lines.push(`Generated by Tag Hunter · taghunter.app`);
  lines.push(`Always verify fees & deadlines at official state agency.`);
  return lines.join("\n");
}

function DeadlinePill({ stateId, species }: { stateId: string; species: string }) {
  const dl = getDeadlineForState(stateId, species);
  if (!dl) return null;
  const now = new Date();
  let year = now.getFullYear();
  let closeDate = new Date(year, dl.closeMonth - 1, dl.closeDay);
  if (closeDate < now) { year++; closeDate = new Date(year, dl.closeMonth - 1, dl.closeDay); }
  const days = Math.ceil((closeDate.getTime() - now.getTime()) / 86400000);
  const color = days <= 14 ? "var(--danger)" : days <= 45 ? "var(--warning)" : "var(--success)";
  return (
    <span style={{ fontSize: 11, fontWeight: 700, padding: "2px 8px", borderRadius: 999, background: `${color}18`, border: `1px solid ${color}40`, color, whiteSpace: "nowrap" }}>
      {APPLY_MONTHS[dl.closeMonth]} {dl.closeDay} · {days}d
    </span>
  );
}

function GuideCard({ guide, species, profile }: { guide: StateApplyGuide; species: string; profile: HunterProfile | null }) {
  const [expanded, setExpanded] = useState(false);
  const [copied, setCopied] = useState(false);
  const hasProfile = profile && profile.firstName && profile.lastName;
  const handleCopy = () => {
    if (!profile) return;
    const text = buildPrefillCard(profile, guide, species);
    navigator.clipboard.writeText(text).then(() => { setCopied(true); setTimeout(() => setCopied(false), 2500); });
  };
  return (
    <div className="card" style={{ overflow: "hidden" }}>
      <div style={{ padding: "16px 20px", display: "flex", alignItems: "center", justifyContent: "space-between", gap: 12, flexWrap: "wrap" }}>
        <div style={{ flex: 1, minWidth: 0 }}>
          <div style={{ display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap", marginBottom: 6 }}>
            <span style={{ fontWeight: 800, fontSize: 15, color: "var(--text)" }}>{guide.stateName}</span>
            {species !== "all" && <DeadlinePill stateId={guide.stateId} species={species} />}
            <span style={{ fontSize: 10, fontWeight: 700, padding: "2px 8px", borderRadius: 999, background: "rgba(96,165,250,0.1)", border: "1px solid rgba(96,165,250,0.25)", color: "#60a5fa", letterSpacing: "0.05em", textTransform: "uppercase" }}>
              Draw Result: {DRAW_RESULT_MONTHS[guide.drawResultMonth]}
            </span>
          </div>
          <p style={{ fontSize: 12, color: "var(--text-3)" }}>{guide.drawResultNote}</p>
        </div>
        <div style={{ display: "flex", gap: 8, flexShrink: 0 }}>
          {hasProfile && (
            <button onClick={handleCopy} className="btn-ghost" style={{ fontSize: 12, padding: "7px 14px" }}>
              {copied ? "✓ Copied!" : "📋 Pre-Fill"}
            </button>
          )}
          <a href={guide.portalUrl} target="_blank" rel="noopener noreferrer" className="btn-primary" style={{ fontSize: 12, padding: "7px 16px" }}>
            Apply →
          </a>
          <button onClick={() => setExpanded(v => !v)} style={{ fontSize: 13, color: "var(--text-3)", background: "none", border: "1px solid var(--border)", borderRadius: 8, padding: "7px 12px", cursor: "pointer" }}>
            {expanded ? "▲" : "▼"}
          </button>
        </div>
      </div>
      {expanded && (
        <div style={{ borderTop: "1px solid var(--border)", padding: 20 }}>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))", gap: 20 }}>
            <div>
              <p className="field-label" style={{ marginBottom: 10 }}>What You Need</p>
              <ul style={{ display: "flex", flexDirection: "column", gap: 6, listStyle: "none", padding: 0 }}>
                {guide.requiredFields.map((f, i) => (
                  <li key={i} style={{ fontSize: 12, color: "var(--text-2)", display: "flex", gap: 8, alignItems: "flex-start" }}>
                    <span style={{ color: "var(--text-3)", flexShrink: 0 }}>·</span>{f}
                  </li>
                ))}
              </ul>
            </div>
            {guide.specialRequirements.length > 0 && (
              <div>
                <p className="field-label" style={{ marginBottom: 10, color: "var(--warning)" }}>Before You Apply</p>
                <ul style={{ display: "flex", flexDirection: "column", gap: 6, listStyle: "none", padding: 0 }}>
                  {guide.specialRequirements.map((r, i) => (
                    <li key={i} style={{ fontSize: 12, color: "var(--text-2)", display: "flex", gap: 8, alignItems: "flex-start" }}>
                      <span style={{ color: "var(--warning)", flexShrink: 0 }}>⚠</span>{r}
                    </li>
                  ))}
                </ul>
              </div>
            )}
            {guide.proTips.length > 0 && (
              <div>
                <p className="field-label" style={{ marginBottom: 10, color: "var(--amber)" }}>Pro Tips</p>
                <ul style={{ display: "flex", flexDirection: "column", gap: 6, listStyle: "none", padding: 0 }}>
                  {guide.proTips.map((t, i) => (
                    <li key={i} style={{ fontSize: 12, color: "var(--text-2)", display: "flex", gap: 8, alignItems: "flex-start" }}>
                      <span style={{ color: "var(--amber)", flexShrink: 0 }}>→</span>{t}
                    </li>
                  ))}
                </ul>
              </div>
            )}
          </div>
          {guide.nrNotes && (
            <div style={{ marginTop: 16, padding: "10px 14px", background: "rgba(249,115,22,0.06)", border: "1px solid rgba(249,115,22,0.2)", borderRadius: 8 }}>
              <p style={{ fontSize: 12, color: "var(--text-2)" }}>
                <span style={{ color: "#f97316", fontWeight: 700 }}>NR Note: </span>{guide.nrNotes}
              </p>
            </div>
          )}
          <div style={{ marginTop: 16, display: "flex", gap: 10, flexWrap: "wrap" }}>
            <a href={guide.portalUrl} target="_blank" rel="noopener noreferrer" style={{ fontSize: 12, color: "var(--amber)" }}>{guide.portalLabel} ↗</a>
            <span style={{ color: "var(--border)", fontSize: 12 }}>·</span>
            <Link href={`/states/${guide.stateId}`} style={{ fontSize: 12, color: "var(--text-3)" }}>State Profile →</Link>
          </div>
        </div>
      )}
    </div>
  );
}

function ApplyTab() {
  const [speciesFilter, setSpeciesFilter] = useState<SpeciesKey | "all">("elk");
  const [profile, setProfile] = useState<HunterProfile | null>(null);
  const [hasProfile, setHasProfile] = useState(false);
  useEffect(() => {
    try {
      const raw = localStorage.getItem(PROFILE_KEY);
      if (raw) { const p = JSON.parse(raw) as HunterProfile; setProfile(p); setHasProfile(!!(p.firstName && p.lastName)); }
    } catch {}
  }, []);
  const guides = speciesFilter === "all" ? STATE_APPLY_GUIDES : STATE_APPLY_GUIDES.filter(g => g.species.includes(speciesFilter));
  const speciesForDeadline = speciesFilter === "all" ? "elk" : speciesFilter;
  const sorted = speciesFilter === "all" ? guides : [...guides].sort((a, b) => {
    const da = getDeadlineForState(a.stateId, speciesForDeadline);
    const db = getDeadlineForState(b.stateId, speciesForDeadline);
    if (!da) return 1; if (!db) return -1;
    const now = new Date();
    const toDate = (d: { closeMonth: number; closeDay: number }) => { let y = now.getFullYear(); let dt = new Date(y, d.closeMonth - 1, d.closeDay); if (dt < now) dt = new Date(y + 1, d.closeMonth - 1, d.closeDay); return dt.getTime(); };
    return toDate(da) - toDate(db);
  });
  return (
    <div>
      <div style={{ display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: 16, marginBottom: 20, flexWrap: "wrap" }}>
        <p style={{ fontSize: 13, color: "var(--text-2)" }}>Official apply links, step-by-step guides, and pre-fill cards for every state.</p>
        <Link href="/profile" className={hasProfile ? "btn-ghost" : "btn-primary"} style={{ fontSize: 12, padding: "8px 16px", flexShrink: 0 }}>
          {hasProfile ? "✓ Profile Set" : "Set Up Profile →"}
        </Link>
      </div>
      {!hasProfile && (
        <div className="card" style={{ padding: "14px 18px", marginBottom: 20, display: "flex", alignItems: "center", gap: 14, background: "rgba(245,158,11,0.06)", borderColor: "rgba(245,158,11,0.25)" }}>
          <span style={{ fontSize: "1.4rem", flexShrink: 0 }}>📋</span>
          <div style={{ flex: 1 }}>
            <p style={{ fontWeight: 700, fontSize: 13, color: "var(--amber)", marginBottom: 2 }}>Set up your Hunter Profile to unlock pre-fill cards</p>
            <p style={{ fontSize: 12, color: "var(--text-3)" }}>Fill your info once — Tag Hunter generates a copy-paste card pre-filled with your details for each state application.</p>
          </div>
          <Link href="/profile" className="btn-primary" style={{ fontSize: 12, padding: "8px 16px", flexShrink: 0 }}>Set Up →</Link>
        </div>
      )}
      <div style={{ display: "flex", flexWrap: "wrap", gap: 6, marginBottom: 20 }}>
        {APPLY_SPECIES_FILTER.map(s => (
          <button key={s.key} onClick={() => setSpeciesFilter(s.key)} className={`pill-btn${speciesFilter === s.key ? " selected" : ""}`} style={{ fontSize: 12, padding: "6px 14px" }}>
            {s.label}
          </button>
        ))}
      </div>
      <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
        {sorted.map(guide => <GuideCard key={guide.stateId} guide={guide} species={speciesForDeadline} profile={profile} />)}
      </div>
      <p style={{ textAlign: "center", fontSize: 11, color: "var(--text-3)", marginTop: 32 }}>
        Always verify deadlines, fees, and requirements at your state&apos;s official wildlife agency before applying.
      </p>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// DEADLINES TAB
// ─────────────────────────────────────────────────────────────────────────────

const ALL_DL_SPECIES: SpeciesKey[] = ["elk", "mule_deer", "whitetail", "pronghorn", "bighorn_sheep", "mountain_goat", "moose", "black_bear", "bison"];
const DL_MONTH_NAMES = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];
const POINT_SYSTEM_LABELS: Record<string, string> = { preference:"Preference pts", bonus:"Bonus pts", weighted:"Weighted pts", none:"Random lottery", otc:"OTC" };

interface DeadlineItem {
  stateId: string; stateName: string; species: SpeciesKey;
  closeMonth: number; closeDay: number; closeYear: number;
  openMonth: number; feeNonresident: number; hasOTC: boolean;
  pointSystem: string; daysUntil: number; isOpenNow: boolean;
}

function getDeadlines(speciesFilter: SpeciesKey | "all"): DeadlineItem[] {
  const now = new Date(); const today = now.getTime(); const currentMonth = now.getMonth() + 1;
  const seen = new Set<string>(); const deadlines: DeadlineItem[] = [];
  for (const d of huntingData) {
    if (speciesFilter !== "all" && d.species !== speciesFilter) continue;
    const key = `${d.stateId}-${d.species}`; if (seen.has(key)) continue; seen.add(key);
    let year = now.getFullYear();
    let closeDate = new Date(year, d.appCloseMonth - 1, d.appCloseDay);
    if (closeDate.getTime() < today) { year += 1; closeDate = new Date(year, d.appCloseMonth - 1, d.appCloseDay); }
    const daysUntil = Math.ceil((closeDate.getTime() - today) / 86400000);
    let isOpenNow = false;
    if (year === now.getFullYear()) {
      if (d.appOpenMonth <= d.appCloseMonth) isOpenNow = currentMonth >= d.appOpenMonth && currentMonth <= d.appCloseMonth && closeDate.getTime() > today;
    } else { isOpenNow = currentMonth >= d.appOpenMonth; }
    deadlines.push({ stateId: d.stateId, stateName: d.stateName, species: d.species as SpeciesKey, closeMonth: d.appCloseMonth, closeDay: d.appCloseDay, closeYear: year, openMonth: d.appOpenMonth, feeNonresident: d.feeNonresident, hasOTC: d.hasOTC, pointSystem: d.pointSystem, daysUntil, isOpenNow });
  }
  return deadlines.sort((a, b) => a.daysUntil - b.daysUntil);
}

function dlUrgencyColor(days: number) { if (days <= 14) return "var(--danger)"; if (days <= 45) return "var(--warning)"; return "var(--success)"; }

function DeadlineCard({ d, watched, onToggle, highlight }: { d: DeadlineItem; watched: boolean; onToggle: () => void; highlight?: boolean }) {
  const color = dlUrgencyColor(d.daysUntil);
  return (
    <div className="card" style={{ padding: "14px 16px", display: "flex", alignItems: "center", justifyContent: "space-between", gap: 16, borderColor: highlight ? "var(--success-border)" : undefined, background: highlight ? "var(--success-bg)" : undefined }}>
      <div style={{ flex: 1, minWidth: 0 }}>
        <div style={{ display: "flex", flexWrap: "wrap", alignItems: "center", gap: 8, marginBottom: 5 }}>
          <span style={{ fontWeight: 800, fontSize: 14, color: "var(--text)" }}>{d.stateName}</span>
          <span style={{ fontSize: 13, color: "var(--text-2)" }}>{SPECIES_LABELS[d.species]}</span>
          {d.isOpenNow && <span className="badge badge-green">OPEN NOW</span>}
          {d.hasOTC && <span className="badge badge-muted">OTC</span>}
        </div>
        <div style={{ display: "flex", flexWrap: "wrap", gap: 10, fontSize: 12, color: "var(--text-3)" }}>
          <span>Closes {DL_MONTH_NAMES[d.closeMonth - 1]} {d.closeDay}, {d.closeYear}</span>
          <span>·</span><span>NR ${d.feeNonresident.toLocaleString()}</span>
          <span>·</span><span>{POINT_SYSTEM_LABELS[d.pointSystem] ?? d.pointSystem}</span>
        </div>
      </div>
      <div style={{ display: "flex", alignItems: "center", gap: 12, flexShrink: 0 }}>
        <button onClick={onToggle} title={watched ? "Remove reminder" : "Set reminder"} style={{ fontSize: "1.1rem", color: watched ? "var(--amber)" : "var(--text-3)", background: "none", border: "none", cursor: "pointer" }}>
          {watched ? "🔔" : "🔕"}
        </button>
        <div style={{ textAlign: "right" }}>
          <div style={{ fontSize: "1.1rem", fontWeight: 800, color, lineHeight: 1 }}>{d.daysUntil}d</div>
          <div style={{ fontSize: 11, color, marginTop: 2 }}>{d.daysUntil <= 14 ? "Closing soon" : d.daysUntil <= 45 ? "Coming up" : "Upcoming"}</div>
        </div>
      </div>
    </div>
  );
}

function DeadlinesTab() {
  const [speciesFilter, setSpeciesFilter] = useState<SpeciesKey | "all">("elk");
  const [watchedKeys, setWatchedKeys] = useState<Set<string>>(new Set());
  const [alertDismissed, setAlertDismissed] = useState(false);
  const [upcomingReminders, setUpcomingReminders] = useState<DeadlineReminder[]>([]);
  useEffect(() => { const r = loadReminders(); setWatchedKeys(new Set(r.map(x => x.key))); setUpcomingReminders(getUpcomingReminders(14)); }, []);
  const deadlines = getDeadlines(speciesFilter);
  const openNow = deadlines.filter(d => d.isOpenNow);
  const upcoming = deadlines.filter(d => !d.isOpenNow && d.daysUntil <= 60);
  const later = deadlines.filter(d => !d.isOpenNow && d.daysUntil > 60);
  const handleToggleReminder = (d: DeadlineItem) => {
    const key = `${d.stateId}-${d.species}`;
    const reminder: DeadlineReminder = { key, stateName: d.stateName, species: d.species, closeMonth: d.closeMonth, closeDay: d.closeDay };
    const nowWatching = toggleReminder(reminder);
    setWatchedKeys(prev => { const next = new Set(prev); if (nowWatching) next.add(key); else next.delete(key); return next; });
    setUpcomingReminders(getUpcomingReminders(14));
  };
  const handleExportIcal = () => {
    const lines = ["BEGIN:VCALENDAR","VERSION:2.0","PRODID:-//Tag Hunter//Hunt Application Deadlines//EN","CALSCALE:GREGORIAN"];
    for (const d of deadlines) {
      const dt = `${d.closeYear}${String(d.closeMonth).padStart(2,"0")}${String(d.closeDay).padStart(2,"0")}`;
      lines.push("BEGIN:VEVENT",`UID:taghunter-${d.stateId}-${d.species}-${d.closeYear}@taghunter.app`,`DTSTART;VALUE=DATE:${dt}`,`DTEND;VALUE=DATE:${dt}`,`SUMMARY:${d.stateName} ${SPECIES_LABELS[d.species]} Application Closes`,`DESCRIPTION:NR Fee: $${d.feeNonresident}`,`END:VEVENT`);
    }
    lines.push("END:VCALENDAR");
    const blob = new Blob([lines.join("\r\n")], { type: "text/calendar;charset=utf-8" });
    const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = "taghunter-deadlines.ics"; a.click(); URL.revokeObjectURL(url);
  };
  return (
    <div>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 16 }}>
        <p style={{ fontSize: 13, color: "var(--text-2)" }}>Never miss an application window</p>
        <button onClick={handleExportIcal} className="btn-ghost" style={{ fontSize: 12 }}>📅 Export .ics</button>
      </div>
      <DataDisclaimer />
      {!alertDismissed && upcomingReminders.length > 0 && (
        <div className="card" style={{ padding: 16, marginBottom: 20, display: "flex", alignItems: "flex-start", gap: 12, background: "var(--warning-bg)", borderColor: "var(--warning-border)" }}>
          <span style={{ fontSize: "1.1rem", flexShrink: 0 }}>🔔</span>
          <div style={{ flex: 1 }}>
            <p style={{ fontWeight: 700, fontSize: 13, color: "var(--warning)", marginBottom: 6 }}>Upcoming deadline reminders</p>
            <ul style={{ listStyle: "none", display: "flex", flexDirection: "column", gap: 4 }}>
              {upcomingReminders.map(r => {
                const now = new Date(); let year = now.getFullYear(); let d = new Date(year, r.closeMonth - 1, r.closeDay); if (d < now) { year += 1; d = new Date(year, r.closeMonth - 1, r.closeDay); }
                const days = Math.ceil((d.getTime() - now.getTime()) / 86400000);
                return <li key={r.key} style={{ fontSize: 12, color: "var(--text-2)" }}>{r.stateName} {SPECIES_LABELS[r.species]} — closes {DL_MONTH_NAMES[r.closeMonth - 1]} {r.closeDay}<span style={{ color: days <= 7 ? "var(--danger)" : "var(--amber)", fontWeight: 700 }}> ({days}d)</span></li>;
              })}
            </ul>
          </div>
          <button onClick={() => setAlertDismissed(true)} style={{ fontSize: 14, color: "var(--text-3)", background: "none", border: "none", cursor: "pointer" }}>✕</button>
        </div>
      )}
      <div style={{ display: "flex", flexWrap: "wrap", gap: 6, marginBottom: 20 }}>
        {(["all", ...ALL_DL_SPECIES] as (SpeciesKey | "all")[]).map(s => (
          <button key={s} onClick={() => setSpeciesFilter(s)} className={`pill-btn${speciesFilter === s ? " selected" : ""}`} style={{ fontSize: 12, padding: "6px 14px" }}>
            {s === "all" ? "All Species" : SPECIES_LABELS[s]}
          </button>
        ))}
      </div>
      {openNow.length > 0 && (
        <div style={{ marginBottom: 24 }}>
          <p className="section-label" style={{ color: "var(--success)" }}>✅ Apply Right Now</p>
          <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
            {openNow.map(d => { const key = `${d.stateId}-${d.species}`; return <DeadlineCard key={key} d={d} watched={watchedKeys.has(key)} onToggle={() => handleToggleReminder(d)} highlight />; })}
          </div>
        </div>
      )}
      {upcoming.length > 0 && (
        <div style={{ marginBottom: 24 }}>
          <p className="section-label" style={{ color: "var(--warning)" }}>⚡ Next 60 Days</p>
          <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
            {upcoming.map(d => { const key = `${d.stateId}-${d.species}`; return <DeadlineCard key={key} d={d} watched={watchedKeys.has(key)} onToggle={() => handleToggleReminder(d)} />; })}
          </div>
        </div>
      )}
      {later.length > 0 && (
        <div>
          <p className="section-label">Later This Season</p>
          <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
            {later.map(d => { const key = `${d.stateId}-${d.species}`; return <DeadlineCard key={key} d={d} watched={watchedKeys.has(key)} onToggle={() => handleToggleReminder(d)} />; })}
          </div>
        </div>
      )}
      <p style={{ textAlign: "center", fontSize: 11, color: "var(--text-3)", marginTop: 32 }}>Always verify deadlines at your state&apos;s official wildlife agency website before applying.</p>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// MY APPLICATIONS TAB
// ─────────────────────────────────────────────────────────────────────────────

type SortKey = "year" | "state" | "species" | "status";

function TrackerTab() {
  const [apps, setApps] = useState<Application[]>([]);
  const [showAdd, setShowAdd] = useState(false);
  const [filterYear, setFilterYear] = useState<number | "all">("all");
  const [filterSpecies, setFilterSpecies] = useState<SpeciesKey | "all">("all");
  const [filterStatus, setFilterStatus] = useState<AppStatus | "all">("all");
  const [sortKey, setSortKey] = useState<SortKey>("year");
  const [confirmDeleteId, setConfirmDeleteId] = useState<string | null>(null);
  const reload = useCallback(() => { const data = loadTracker(); setApps(data.applications); }, []);
  useEffect(() => { reload(); }, [reload]);
  const handleStatusChange = (id: string, status: AppStatus) => { updateApplication(id, { status }); reload(); };
  const handleDelete = (id: string) => { deleteApplication(id); setConfirmDeleteId(null); reload(); };
  const totalFees = apps.reduce((s, a) => s + (a.feeSpent || 0), 0);
  const drawn = apps.filter(a => a.status === "drawn").length;
  const thisYear = apps.filter(a => a.year === CURRENT_YEAR);
  const pending = apps.filter(a => a.status === "applied" || a.status === "pending");
  const currentPoints = deriveCurrentPoints(apps);
  const years = [...new Set(apps.map(a => a.year))].sort((a, b) => b - a);
  const allSpecies = [...new Set(apps.map(a => a.species))] as SpeciesKey[];
  const filtered = apps
    .filter(a => filterYear === "all" || a.year === filterYear)
    .filter(a => filterSpecies === "all" || a.species === filterSpecies)
    .filter(a => filterStatus === "all" || a.status === filterStatus)
    .sort((a, b) => {
      if (sortKey === "year") return b.year - a.year;
      if (sortKey === "state") return a.stateName.localeCompare(b.stateName);
      if (sortKey === "species") return a.species.localeCompare(b.species);
      if (sortKey === "status") return a.status.localeCompare(b.status);
      return 0;
    });
  return (
    <div>
      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 20 }}>
        <p style={{ fontSize: 13, color: "var(--text-2)" }}>Track points, draws, and licenses — stored in your browser</p>
        <div style={{ display: "flex", gap: 8 }}>
          {apps.length > 0 && <button onClick={() => exportToCSV(apps)} className="btn-ghost" style={{ fontSize: 12 }}>↓ CSV</button>}
          <button onClick={() => setShowAdd(true)} className="btn-primary" style={{ fontSize: 13, padding: "8px 16px" }}>+ Log Application</button>
        </div>
      </div>
      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(140px, 1fr))", gap: 12, marginBottom: 24 }}>
        {[
          { label: "Total Applications", value: apps.length },
          { label: "Tags Drawn", value: `${drawn} / ${apps.length}` },
          { label: `${CURRENT_YEAR} Apps`, value: thisYear.length },
          { label: "Fees (All Time)", value: `$${totalFees.toLocaleString()}` },
        ].map(s => (
          <div key={s.label} className="stat-card"><div className="stat-value">{s.value}</div><div className="stat-label">{s.label}</div></div>
        ))}
      </div>
      {pending.length > 0 && (
        <div className="card" style={{ padding: 16, marginBottom: 20, background: "var(--warning-bg)", borderColor: "var(--warning-border)", display: "flex", alignItems: "flex-start", gap: 12 }}>
          <span style={{ fontSize: "1.1rem" }}>⏳</span>
          <div>
            <p style={{ fontWeight: 700, fontSize: 13, color: "var(--warning)" }}>{pending.length} application{pending.length > 1 ? "s" : ""} awaiting results</p>
            <p style={{ fontSize: 12, color: "var(--text-2)", marginTop: 4 }}>{pending.map(a => `${a.stateName} ${SPECIES_LABELS[a.species as SpeciesKey]}`).join(" · ")}</p>
          </div>
        </div>
      )}
      <BudgetDashboard apps={apps} />
      <PointsTracker apps={apps} />
      <LicenseTracker />
      <HuntLogbook />
      {Object.keys(currentPoints).length > 0 && (
        <div className="card" style={{ padding: 20, marginBottom: 20 }}>
          <h3 style={{ fontSize: 11, fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.08em", color: "var(--text-3)", marginBottom: 14 }}>Current Points (derived from history)</h3>
          <div style={{ display: "flex", flexWrap: "wrap", gap: 8 }}>
            {Object.entries(currentPoints).flatMap(([stateId, speciesMap]) =>
              Object.entries(speciesMap).map(([species, pts]) => (
                <div key={`${stateId}-${species}`} className="badge badge-muted" style={{ padding: "4px 10px", borderRadius: 6 }}>
                  <span style={{ color: "var(--text)" }}>{STATE_NAMES[stateId.toUpperCase()] ?? stateId}</span>
                  <span style={{ color: "var(--text-3)", margin: "0 4px" }}>·</span>
                  <span style={{ color: "var(--text-2)" }}>{SPECIES_LABELS[species as SpeciesKey]}</span>
                  <span style={{ color: "var(--amber)", fontWeight: 800, marginLeft: 6 }}>{pts}pt</span>
                </div>
              ))
            )}
          </div>
        </div>
      )}
      {apps.length > 0 && (
        <div style={{ display: "flex", flexWrap: "wrap", gap: 8, marginBottom: 16, alignItems: "center" }}>
          <select value={filterYear} onChange={e => setFilterYear(e.target.value === "all" ? "all" : Number(e.target.value))} className="input" style={{ width: "auto", fontSize: 12, padding: "6px 10px" }}>
            <option value="all">All Years</option>
            {years.map(y => <option key={y} value={y}>{y}</option>)}
          </select>
          <select value={filterSpecies} onChange={e => setFilterSpecies(e.target.value as SpeciesKey | "all")} className="input" style={{ width: "auto", fontSize: 12, padding: "6px 10px" }}>
            <option value="all">All Species</option>
            {allSpecies.map(s => <option key={s} value={s}>{SPECIES_LABELS[s]}</option>)}
          </select>
          <select value={filterStatus} onChange={e => setFilterStatus(e.target.value as AppStatus | "all")} className="input" style={{ width: "auto", fontSize: 12, padding: "6px 10px" }}>
            <option value="all">All Statuses</option>
            {(Object.keys(STATUS_LABELS) as AppStatus[]).map(s => <option key={s} value={s}>{STATUS_LABELS[s]}</option>)}
          </select>
          <div style={{ marginLeft: "auto", display: "flex", alignItems: "center", gap: 6, fontSize: 12, color: "var(--text-3)" }}>
            Sort:
            {(["year","state","species","status"] as SortKey[]).map(k => (
              <button key={k} onClick={() => setSortKey(k)} style={{ padding: "4px 10px", borderRadius: 6, fontSize: 12, fontWeight: sortKey === k ? 700 : 500, background: sortKey === k ? "var(--amber-glow)" : "transparent", color: sortKey === k ? "var(--amber)" : "var(--text-3)", border: sortKey === k ? "1px solid rgba(232,150,15,0.3)" : "1px solid transparent", cursor: "pointer", textTransform: "capitalize" }}>
                {k}
              </button>
            ))}
          </div>
        </div>
      )}
      {apps.length === 0 ? (
        <div className="card" style={{ padding: 56, textAlign: "center" }}>
          <div style={{ fontSize: "2.5rem", marginBottom: 16 }}>📋</div>
          <p style={{ fontWeight: 700, fontSize: 15, marginBottom: 8 }}>No applications logged yet</p>
          <p style={{ fontSize: 13, color: "var(--text-2)", marginBottom: 24, maxWidth: 400, margin: "0 auto 24px" }}>Track every state application, watch your points grow, and never miss a deadline.</p>
          <button onClick={() => setShowAdd(true)} className="btn-primary">Log Your First Application</button>
        </div>
      ) : (
        <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
          {filtered.length === 0 && <p style={{ textAlign: "center", padding: "32px 0", fontSize: 13, color: "var(--text-3)" }}>No applications match the current filters.</p>}
          {filtered.map(app => {
            const colors = STATUS_COLORS[app.status];
            const isConfirmingDelete = confirmDeleteId === app.id;
            return (
              <div key={app.id} className="card" style={{ padding: 16 }}>
                <div style={{ display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: 16 }}>
                  <div style={{ flex: 1, minWidth: 0 }}>
                    <div style={{ display: "flex", flexWrap: "wrap", alignItems: "center", gap: 8, marginBottom: 6 }}>
                      <span style={{ fontWeight: 800, fontSize: 14, color: "var(--text)" }}>{app.year}</span>
                      <span style={{ fontWeight: 700, fontSize: 14, color: "var(--amber)" }}>{app.stateName}</span>
                      <span style={{ fontSize: 14, color: "var(--text-2)" }}>{SPECIES_LABELS[app.species as SpeciesKey]}</span>
                      <span style={{ fontSize: 12, color: "var(--text-3)", textTransform: "capitalize" }}>{app.seasonType}</span>
                    </div>
                    <div style={{ display: "flex", flexWrap: "wrap", gap: 12, fontSize: 12, color: "var(--text-3)" }}>
                      {app.pointsBefore >= 0 && <span>Points: <span style={{ color: "var(--text)" }}>{app.pointsBefore}</span>{app.pointsAfter !== app.pointsBefore && <span> → <span style={{ color: app.status === "drawn" ? "var(--danger)" : "var(--success)" }}>{app.pointsAfter}</span></span>}</span>}
                      {app.feeSpent > 0 && <span>Fee: <span style={{ color: "var(--text)" }}>${app.feeSpent}</span></span>}
                      {app.appliedDate && <span>Applied: {app.appliedDate}</span>}
                      {app.notes && <span style={{ fontStyle: "italic" }}>"{app.notes}"</span>}
                    </div>
                  </div>
                  <div style={{ display: "flex", flexDirection: "column", alignItems: "flex-end", gap: 8, flexShrink: 0 }}>
                    <span className="badge" style={{ background: colors.bg, border: `1px solid ${colors.border}`, color: colors.text, borderRadius: 6, padding: "3px 10px" }}>{STATUS_LABELS[app.status]}</span>
                    {(app.status === "applied" || app.status === "pending") && (
                      <div style={{ display: "flex", gap: 6 }}>
                        <button onClick={() => handleStatusChange(app.id, "drawn")} className="badge badge-green" style={{ cursor: "pointer", padding: "3px 10px", borderRadius: 6 }}>Drawn ✓</button>
                        <button onClick={() => handleStatusChange(app.id, "not_drawn")} className="badge badge-red" style={{ cursor: "pointer", padding: "3px 10px", borderRadius: 6 }}>Not Drawn</button>
                      </div>
                    )}
                    {isConfirmingDelete ? (
                      <div style={{ display: "flex", gap: 6 }}>
                        <button onClick={() => handleDelete(app.id)} style={{ fontSize: 11, padding: "2px 8px", borderRadius: 4, background: "var(--danger-bg)", color: "var(--danger)", border: "1px solid var(--danger-border)", cursor: "pointer" }}>Confirm Delete</button>
                        <button onClick={() => setConfirmDeleteId(null)} style={{ fontSize: 11, color: "var(--text-3)", cursor: "pointer", background: "none", border: "none" }}>Cancel</button>
                      </div>
                    ) : (
                      <button onClick={() => setConfirmDeleteId(app.id)} style={{ fontSize: 11, color: "var(--text-3)", cursor: "pointer", background: "none", border: "none" }}>Delete</button>
                    )}
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      )}
      <p style={{ textAlign: "center", fontSize: 11, color: "var(--text-3)", marginTop: 32 }}>Data stored locally in your browser. Use Export CSV to back up your records.</p>
      {showAdd && <AddApplicationModal onClose={() => setShowAdd(false)} onAdded={() => { reload(); setShowAdd(false); }} />}
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// DASHBOARD PAGE
// ─────────────────────────────────────────────────────────────────────────────

type Tab = "apply" | "deadlines" | "tracker";

const TAB_CONFIG: { key: Tab; label: string; emoji: string }[] = [
  { key: "apply",     label: "Apply",          emoji: "🗂️" },
  { key: "deadlines", label: "Deadlines",       emoji: "📅" },
  { key: "tracker",   label: "My Applications", emoji: "📋" },
];

function DashboardInner() {
  const searchParams = useSearchParams();
  const router = useRouter();
  const rawTab = searchParams.get("tab");
  const activeTab: Tab = (rawTab === "apply" || rawTab === "deadlines" || rawTab === "tracker") ? rawTab : "apply";

  const setTab = (t: Tab) => {
    const params = new URLSearchParams(searchParams.toString());
    params.set("tab", t);
    router.replace(`/dashboard?${params.toString()}`, { scroll: false });
  };

  return (
    <div className="page">
      <AppNav />
      <div className="page-inner">

        {/* Page header */}
        <div style={{ marginBottom: 24 }}>
          <h1 style={{ fontSize: "1.4rem", fontWeight: 800, letterSpacing: "-0.02em" }}>Dashboard</h1>
          <p style={{ fontSize: 13, color: "var(--text-2)", marginTop: 4 }}>Apply, track deadlines, and manage your applications in one place.</p>
        </div>

        {/* Tab bar */}
        <div style={{ display: "flex", gap: 4, borderBottom: "1px solid var(--border)", marginBottom: 28 }}>
          {TAB_CONFIG.map(t => (
            <button
              key={t.key}
              onClick={() => setTab(t.key)}
              style={{
                padding: "10px 16px",
                fontSize: 14,
                fontWeight: activeTab === t.key ? 700 : 500,
                color: activeTab === t.key ? "var(--amber)" : "var(--text-3)",
                background: "none",
                border: "none",
                borderBottom: activeTab === t.key ? "2px solid var(--amber)" : "2px solid transparent",
                cursor: "pointer",
                marginBottom: -1,
                display: "flex",
                alignItems: "center",
                gap: 6,
                transition: "color 0.15s",
                whiteSpace: "nowrap",
              }}
            >
              <span style={{ fontSize: "1rem" }}>{t.emoji}</span>
              {t.label}
            </button>
          ))}
        </div>

        {/* Tab content */}
        {activeTab === "apply"     && <ApplyTab />}
        {activeTab === "deadlines" && <DeadlinesTab />}
        {activeTab === "tracker"   && <TrackerTab />}

      </div>
    </div>
  );
}

export default function DashboardPage() {
  return (
    <Suspense fallback={
      <div className="min-h-screen flex items-center justify-center" style={{ color: "var(--text-3)" }}>
        Loading...
      </div>
    }>
      <DashboardInner />
    </Suspense>
  );
}
